import {useEffect, useState} from "react";
import useAvailability from "./useAvailability";

export const useBooks = () => {
    let [books, setBooks] = useState([]);



    useEffect(() => {
        //fetch(process.env.REACT_APP_GW_URL).then((res) => res.json()).then((res) => setRestaurants(res));

        setTimeout(() => {
            setBooks([
                { id: "0",title: "Dispersión ", author: " Iain Reid", yearPublication:"2023",   caratula:"https://random.imagecdn.app/200/250", availability: "23", sinopsis: "Penny es artista y lleva varias décadas viviendo en el mismo apartamento, rodeada de los objetos y los recuerdos de su larga vida. Resignada a los rituales triviales de la vejez, un día empieza a sufrir lapsus. Años atrás, antes de que falleciera el que había sido su pareja durante mucho tiempo, se hicieron preparativos, sin que ella lo supiera, para reservarle una habitación en una singular residencia en la que, tras sufrir demasiados «incidentes», acaba ingresando." , genre: "Terror", puntuation: "3.23", tags:"New release" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "1",title: "Los siete maridos de Evelyn Hugo", author: "Taylor Jenkins Reid", yearPublication:"2017",   caratula:"https://random.imagecdn.app/200/251", availability: "4", sinopsis: "Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself. Why her? Why now?" , genre: "Romántica", puntuation: "3.45", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "2",title: "Deep Sniff", author: "Adam Zmith", yearPublication:"2021",   caratula:"https://random.imagecdn.app/200/252", availability: "15", sinopsis: "This is the intriguing story of how poppers wafted out of the lab and into gay bars, corner shops, bedrooms and porn supercuts. Blending historical research with wry observation, Adam Zmith explores the cultural forces and improbable connections behind the power of poppers. What emerges is not just a history of pub raids, viral panics and pecs the size of dinner plates. It is a collection of fresh and provocative ideas about identity, sex, utopia, capitalism, law, freedom and the bodies that we use to experience the world. " , genre: "Histórica", puntuation: "4.12", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "3",title: "Los hombres que no amaban a las mujeres", author: "Stieg Larsson", yearPublication:"2015",   caratula:"https://random.imagecdn.app/200/253", availability: "7", sinopsis: "Harriet Vanger desapareció hace treinta y seis años en una isla sueca propiedad de su poderosa familia. A pesar del despliegue policial, no se encontró ni rastro de la muchacha. ¿Se escapó? ¿Fue secuestrada? ¿Asesinada? El caso está cerrado y los detalles olvidados. Pero su tío Henrik Vanger, un empresario retirado, vive obsesionado con resolver el misterio antes de morir." , genre: "Thriller", puntuation: "1.76", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "4",title: "It", author: "Stephen King", yearPublication:"1986",   caratula:"https://random.imagecdn.app/200/254", availability: "9", sinopsis: "¿Quién o qué mutila y mata a los niños de un pequeño pueblo norteamericano?¿Por qué llega cíclicamente el horror a Derry en forma de un payaso siniestro que va sembrando la destrucción a su paso?" , genre: "Terror", puntuation: "3.89", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "5",title: "The Helsinki Affair", author: "Anna Pitoniak", yearPublication:"2023",   caratula:"https://random.imagecdn.app/200/255", availability: "3", sinopsis: " CIA agent Amanda Cole is thrust into an international conspiracy involving high-profile assassinations and Russian blackmail. It ’ s the case of her lifetime, but solving it might require her to betray another spy—who just so happens to be her father. " , genre: "Thiller", puntuation: "2.31", tags:"New release" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "6",title: "Seis de Cuervos", author: "Leigh Bardugo", yearPublication:"2014",   caratula:"https://random.imagecdn.app/200/258", availability: "19", sinopsis: "Ketterdam: a bustling hub of international trade where anything can be had for the right price—and no one knows that better than criminal prodigy Kaz Brekker. Kaz is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can’t pull it off alone. . . ." , genre: "Fantasía", puntuation: "1.98", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "7",title: "La Comunidad del Anillo", author: "J.R.R Tolkien", yearPublication:"1954",   caratula:"https://random.imagecdn.app/200/257", availability: "8", sinopsis: "En la adormecida e idílica Comarca, un joven hobbit recibe un encargo: custodiar el Anillo Único y emprender el viaje para su destrucción en la Grieta del Destino. Acompañado por magos, hombres, elfos y enanos, atravesará la Tierra Media y se internará en las sombras de Mordor, perseguido siempre por las huestes de Sauron, el Señor Oscuro, dispuesto a recuperar su creación para establecer el dominio definitivo del Mal." , genre: "Fantasía", puntuation: "4.67", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "8",title: "El imperio final", author: "Brandon Sanderson", yearPublication:"2020",   caratula:"https://random.imagecdn.app/200/259", availability: "14", sinopsis: "Durante mil años han caído cenizas del cielo. Durante mil años nada ha  florecido. Durante mil años los skaa han sido esclavizados y viven en la  miseria, sumidos en un miedo inevitable. Durante mil años el Lord  Legislador ha reinado con poder absoluto, dominando gracias al terror, a  sus poderes y a su inmortalidad, ayudado por «obligadores» e «inquisidores», junto a la poderosa magia de la alomancia." , genre: "Fantasía", puntuation: "4.75", tags:"",loaned: "no",initialDate: "" , loanedDate:""},
                { id: "9",title: "1776", author: "David McCullough", yearPublication:"2005",   caratula:"https://random.imagecdn.app/201/250", availability: "2", sinopsis: "In this masterful book, David McCullough tells the intensely human story of those who marched with General George Washington in the year of the Declaration of Independence - when the whole American cause was riding on their success, without which all hope for independence would have been dashed and the noble ideals of the Declaration would have amounted to little more than words on paper." , genre: "Histórica", puntuation: "3.7", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "10",title: "Land of Milk and Honey", author: "C Pam Zhang", yearPublication:"2023",   caratula:"https://random.imagecdn.app/202/250", availability: "6", sinopsis: "A smog has spread. Food crops are rapidly disappearing. A chef escapes her dying career in a dreary city to take a job at a decadent mountaintop colony seemingly free of the world's troubles. " , genre: "Fantasía", puntuation: "4.30", tags:"New release" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "11",title: "La condesa sangrienta", author: "Alejandra Pizarnik", yearPublication:"1966",   caratula:"https://random.imagecdn.app/203/250", availability: "8", sinopsis: "Acusada del asesinato de 650 jóvenes, Erzébet Báthory es una de las criminales más siniestras de la historia. En su castillo de los Cárpatos, a finales del siglo XVII, la condesa se cierne sobre sus víctimas para desangrarlas y conservar su juventud. Su leyenda maldita y fascinante pervive en el tiempo. La condesa sangrienta es una de las composiciones clave de Alejandra Pizarnik, sus páginas construyen un retrato perturbador del sadismo y la locura que las estampas del artista Santiago Caruso recrean con admirable maestría." , genre: "Terror", puntuation: "2.4", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "12",title: "Siempre hemos vivido en el castillo", author: "Shirley Jackson", yearPublication:"1962",   caratula:"https://random.imagecdn.app/204/250", availability: "3", sinopsis: "Merricat lleva una vida solitaria en una gran casa apartada del pueblo. Allí pasa las horas recluida con su bella hermana mayor y su anciano tío Julián. En el hogar de los Blackwood los días discurrían apacibles si no fuera porque los otros miembros de la familia murieron envenenados allí mismo, en el comedor, seis años atrás." , genre: "Terror", puntuation: "4.7", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "13",title: "Frankestein", author: "Mary Shelley", yearPublication:"1818",   caratula:"https://random.imagecdn.app/205/250", availability: "12", sinopsis: "Frankenstein; or, The Modern Prometheus is a novel written by the English author Mary Wollstonecraft Shelley that tells the story of a young science student Victor Frankenstein, who creates a grotesque but sentient creature in an unorthodox scientific experiment. Shelley started writing the story when she was 18, and the first edition of the novel was published anonymously in London in 1818, when she was 20. Shelley's name first appeared on the second edition, published in France in 1823." , genre: "Terror", puntuation: "3.84", tags:"" ,loaned: "yes",initialDate: "10/12/2023" , loanedDate:"16/12/2023"},
                { id: "14",title: "House of Leaves", author: "Mark Z. Danielewski", yearPublication:"2000",   caratula:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1403889034i/24800.jpg", availability: "4", sinopsis: "A young family moves into a small home on Ash Tree Lane where they discover something is terribly wrong: their house is bigger on the inside than it is on the outside." , genre: "Terror", puntuation: "4.09", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},
                { id: "15",title: "Carmilla", author: "J. Sheridan Le Fanu", yearPublication:"1872",   caratula:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657795822i/48037.jpg", availability: "30", sinopsis: "In an isolated castle deep in the Austrian forest, Laura leads a solitary life with only her ailing father for company. Until one moonlit night, a horse-drawn carriage crashes into view, carrying an unexpected guest – the beautiful Carmilla. So begins a feverish friendship between Laura and her mysterious, entrancing companion. " , genre: "Terror", puntuation: "3.85", tags:"" ,loaned: "no",initialDate: "" , loanedDate:""},

            ]);
        }, 2500);
    }, []);

    const {updateBookAvailability} = useAvailability(setBooks);


    return {books, setBooks, updateBookAvailability};

}